version: '3'
services:
  lb1:
    build: base/haproxy
    volumes: 
      - ./base/haproxy:/tmp
    hostname: lb1
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    networks:
        client_net:
            ipv4_address: 178.9.2.200
        server_net:
            ipv4_address: 187.2.9.100

  lb2:
    build: base/haproxy1
    volumes: 
      - ./base/haproxy1:/tmp
    hostname: lb2
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    networks:
        client_net:
            ipv4_address: 178.9.2.210
        server_net:
            ipv4_address: 187.2.9.110

  h1:
    build: base/cliente
    hostname: h1
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    depends_on:
      - "lb1"
    networks:
        client_net:
            ipv4_address: 178.9.2.204

  h2:
    build: base/cliente
    hostname: h2
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    depends_on:
      - "lb1"
    networks:
        client_net:
            ipv4_address: 178.9.2.205

  s1:
    hostname: s1
    build: base/servidor
    ports:
          - "8080:80"
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    depends_on:
      - "lb1"
    networks:
      server_net:
        ipv4_address: 187.2.9.101

  s2:
    hostname: s2
    build: base/servidor
    ports:
          - "8081:80"
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    depends_on:
      - "lb1"
    networks:
        server_net:
            ipv4_address: 187.2.9.102
 
  s3:
    hostname: s3
    build: base/servidor
    ports:
          - "8082:80"
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    depends_on:
      - "lb1"
    networks:
        server_net:
            ipv4_address: 187.2.9.103  
         
networks:
  client_net:
    driver: bridge
    ipam:
     config:
       - subnet: 178.9.2.0/24
    driver_opts:
     com.docker.network.bridge.name: client_net
  server_net:
    driver: bridge
    ipam:
     config:
       - subnet: 187.2.9.0/24
    driver_opts:
     com.docker.network.bridge.name: server_net
